Under construction
==================

This section is actually under construction.

You know, it is hard to code a game engine, document it, package it, create games with it, document them, screenshot them, create the engine's website and also breathe when you are just one person.

But, hey, I'll pretty much accept any help if you are interested!

These are things that I surely could use some help:

* Keep improving Gear2D code
* Create better and more useful components
* Support scene and object creation with lua and not only with yaml
* Develop a lot of code examples and create tutorials around them
* Create a lot of games to showcase Gear2D features
* A tool to set up a environment for users to create new games (skeleton directories, cmake templates, etc)
* A tool to bootstrap Gear2D compilation and integrate it with the above tool

The [contact](contact.html) page has information on how to reach me.